spring:
  datasource:
    url: jdbc:mysql://172.16.255.167:3306/pdd?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:h2:mem:atlas;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver